const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d'),W=886,H=1273,img=new Image();img.src='public/marty-party.png';
const ui={score:$('#score'),high:$('#high-score'),ball:$('#ball-count'),card:$('#start-card'),pause:$('#pause-card'),pauseBtn:$('#pause'),toast:$('#toast'),combo:$('#combo'),mission:$('#mission-name'),lights:[...document.querySelectorAll('#mission-lights i')],multi:$('#multiplier'),meter:$('#launch-meter'),meterFill:$('#launch-meter i'),initials:$('#initials-card')};
let running=false,paused=false,score=0,ballNumber=1,last=0,soundOn=true,shake=0,particles=[],floaters=[],audio,musicTimer,charge=0,charging=false,multiplier=1,combo=0,lastHit=0,high=JSON.parse(localStorage.getItem('martyPartyHigh')||'{"score":0,"initials":"---"}');
const keys={left:false,right:false},balls=[],flippers=[{x:292,y:867,len:118,a:.43,rest:.43,omega:0},{x:594,y:867,len:118,a:Math.PI-.43,rest:Math.PI-.43,omega:0}],walls=[[146,440,115,700],[115,700,85,997],[85,997,290,1090],[741,441,775,705],[775,705,817,1002],[817,1002,594,1090],[146,440,265,420],[265,420,620,420],[620,420,741,441],[705,484,760,944]],slings=[{x1:175,y1:790,x2:303,y2:845},{x1:711,y1:790,x2:583,y2:845}];
const targets=[{id:'turtle',x:246,y:563,r:41,c:'#38b9e6',pts:600,label:'TURTLE',group:'sports'},{id:'soccer',x:369,y:522,r:35,c:'#fff2b4',pts:750,label:'SOCCER',group:'sports'},{id:'basketball',x:482,y:529,r:36,c:'#ff8730',pts:750,label:'BASKETBALL',group:'sports'},{id:'baseball',x:447,y:574,r:31,c:'#f7eee2',pts:500,label:'BASEBALL',group:'sports'},{id:'bunny',x:611,y:565,r:40,c:'#ffd052',pts:600,label:'BUNNY',group:'sports'},{id:'cake',x:441,y:698,r:65,c:'#ffd052',pts:1200,label:'CAKE',group:'cake'}];
const pegs=[{x:330,y:648},{x:366,y:635},{x:518,y:646},{x:551,y:668},{x:286,y:741},{x:597,y:748}],candles=[{x:400,y:653},{x:421,y:647},{x:443,y:644},{x:465,y:647},{x:486,y:653}],party=[{x:281,y:707,l:'P'},{x:309,y:731,l:'A'},{x:337,y:753,l:'R'},{x:547,y:753,l:'T'},{x:575,y:731,l:'Y'}],imageRails=[[207,485,226,610],[226,610,275,682],[676,485,655,610],[655,610,610,682],[192,700,245,784],[694,700,640,784]],occluders=[[268,446,124,86],[494,444,127,92],[574,428,106,72],[382,628,122,132]],rampPaths={left:[{x:225,y:810},{x:155,y:700},{x:180,y:520},{x:300,y:455}],right:[{x:661,y:810},{x:730,y:700},{x:704,y:520},{x:585,y:455}],cake:[{x:441,y:800},{x:430,y:755},{x:450,y:650},{x:441,y:605}]};
const missions=[{name:'SPORTS SWEEP',need:4},{name:'LIGHT THE CANDLES',need:5},{name:'SPELL PARTY',need:5}];let mission=0,progress=new Set();
function makeBall(x=756,y=928,vx=0,vy=0){return{x,y,vx,vy,r:13,spin:0,trail:[],active:vy!==0,lastFlip:0,ramp:null,rampT:0}}
function initAudio(){audio??=new(window.AudioContext||window.webkitAudioContext)()}function tone(f=180,d=.06,type='square',v=.035,delay=0){if(!soundOn)return;initAudio();const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+delay;o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g).connect(audio.destination);o.start(t);o.stop(t+d)}
function chord(){[392,494,587,784].forEach((f,i)=>tone(f,.16,'triangle',.035,i*.06))}function partyBeat(){clearInterval(musicTimer);musicTimer=setInterval(()=>{if(running&&!paused&&soundOn)tone([110,147,165,196][Math.floor(performance.now()/450)%4],.12,'triangle',.012)},450)}
function hud(){ui.score.textContent=String(score).padStart(6,'0').replace(/\B(?=(\d{3})+(?!\d))/g,',');ui.ball.textContent=`${Math.min(ballNumber,3)} / 3`;ui.high.textContent=`${high.initials} ${high.score.toLocaleString()}`;ui.multi.textContent=`${multiplier}X`;ui.mission.textContent=`MISSION: ${missions[mission].name}`;ui.lights.forEach((l,i)=>l.classList.toggle('on',i<progress.size))}
let toastTimer,comboTimer;function say(s){ui.toast.textContent=s;ui.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),950)}function boom(s){ui.combo.textContent=s;ui.combo.classList.add('show');clearTimeout(comboTimer);comboTimer=setTimeout(()=>ui.combo.classList.remove('show'),650)}
function resetBall(){balls.length=0;balls.push(makeBall());charge=0;charging=false;updateMeter()}function newGame(){score=0;ballNumber=1;multiplier=1;combo=0;mission=0;progress.clear();running=true;paused=false;particles=[];floaters=[];resetBall();ui.card.classList.add('hidden');ui.pause.classList.remove('show');ui.initials.classList.remove('show');ui.pauseBtn.textContent='PAUSE';hud();say('HOLD SPACE — RELEASE TO LAUNCH');partyBeat();canvas.focus()}
function startCharge(){if(!running||paused||!balls.some(b=>!b.active))return;charging=true;ui.meter.classList.add('active');tone(95,.06,'sawtooth',.02)}function releaseLaunch(){if(!charging)return;charging=false;const b=balls.find(b=>!b.active);if(b){b.active=true;b.vx=-2.2;b.vy=-(14+charge*12);b.spin=-.15;tone(90+charge*100,.18,'sawtooth',.06)}charge=0;updateMeter()}function updateMeter(){ui.meterFill.style.height=`${Math.max(8,charge*100)}%`;ui.meter.classList.toggle('active',charging)}
function togglePause(force){if(!running)return;paused=typeof force==='boolean'?force:!paused;ui.pause.classList.toggle('show',paused);ui.pauseBtn.textContent=paused?'RESUME':'PAUSE';last=performance.now();if(!paused)canvas.focus()}
function register(id){if(mission===0&&['soccer','basketball','baseball','turtle'].includes(id))progress.add(id);if(mission===1&&id==='cake'&&progress.size<5)progress.add(`c${progress.size}`);if(mission===2){const next=party[progress.size];if(next)progress.add(next.l)}hud();if(progress.size>=missions[mission].need)completeMission()}
function completeMission(){score+=5000*multiplier;multiplier=Math.min(5,multiplier+1);boom(`MISSION COMPLETE • ${multiplier}X`);chord();mission=(mission+1)%missions.length;progress.clear();multiball();hud()}function multiball(){const seed=balls[0]||makeBall(441,700);balls.push(makeBall(seed.x-15,seed.y,-8,-13),makeBall(seed.x+15,seed.y,8,-13));boom('MULTIBALL!')}
function addScore(n,label,x,y){const now=performance.now();combo=now-lastHit<1500?combo+1:1;lastHit=now;const earned=n*multiplier*combo;score+=earned;shake=Math.min(12,shake+3);floaters.push({x,y,text:`+${earned.toLocaleString()}`,t:1});if(combo>1)boom(`${combo} HIT COMBO!`);hud();tone(220+n/6,.07);for(let i=0;i<14;i++)particles.push({x,y,vx:(Math.random()-.5)*9,vy:(Math.random()-.5)*9,t:1,c:['#ffc84a','#ff7627','#58d5ea'][i%3]})}
function lineHit(b,x1,y1,x2,y2,bounce=.84,kick=0){const dx=x2-x1,dy=y2-y1,l2=dx*dx+dy*dy,t=Math.max(0,Math.min(1,((b.x-x1)*dx+(b.y-y1)*dy)/l2)),px=x1+t*dx,py=y1+t*dy,nx=b.x-px,ny=b.y-py,d=Math.hypot(nx,ny);if(d<b.r+5&&d>0){const ux=nx/d,uy=ny/d,dot=b.vx*ux+b.vy*uy;if(dot<0){b.x=px+ux*(b.r+6);b.y=py+uy*(b.r+6);b.vx-=(1+bounce)*dot*ux;b.vy-=(1+bounce)*dot*uy-kick;b.spin+=(dy*b.vx-dx*b.vy)/l2*.12;tone(kick?155:105,.025,'square',kick?.05:.018);return true}}return false}
function flipperHit(b,f){const ex=f.x+Math.cos(f.a)*f.len,ey=f.y+Math.sin(f.a)*f.len,dx=ex-f.x,dy=ey-f.y,l2=dx*dx+dy*dy,t=Math.max(0,Math.min(1,((b.x-f.x)*dx+(b.y-f.y)*dy)/l2)),px=f.x+t*dx,py=f.y+t*dy,nx=b.x-px,ny=b.y-py,d=Math.hypot(nx,ny),radius=b.r+14;if(!d||d>=radius)return false;const ux=nx/d,uy=ny/d,arm=t*f.len,svx=-Math.sin(f.a)*arm*f.omega,svy=Math.cos(f.a)*arm*f.omega,rvx=b.vx-svx,rvy=b.vy-svy,normalSpeed=rvx*ux+rvy*uy;b.x=px+ux*(radius+.5);b.y=py+uy*(radius+.5);if(normalSpeed<0){const impulse=-(1.38)*normalSpeed;b.vx+=impulse*ux;b.vy+=impulse*uy;const tx=-uy,ty=ux,slip=(b.vx*tx+b.vy*ty)-(svx*tx+svy*ty);b.vx-=slip*.08*tx;b.vy-=slip*.08*ty;b.spin+=slip*.012;tone(82+Math.min(70,Math.abs(f.omega)*420),.045,'square',.045);return true}return false}
function targetHit(b,o){const dx=b.x-o.x,dy=b.y-o.y,d=Math.hypot(dx,dy),rr=b.r+o.r;if(d<rr&&d){const nx=dx/d,ny=dy/d,s=Math.max(12,Math.hypot(b.vx,b.vy)*1.06);b.x=o.x+nx*rr;b.y=o.y+ny*rr;b.vx=nx*s+b.spin*2;b.vy=ny*s-1;o.hit=1;register(o.id);addScore(o.pts,o.label,o.x,o.y);return true}return false}
function bezier(path,t){const u=1-t,a=u*u*u,b=3*u*u*t,c=3*u*t*t,d=t*t*t;return{x:a*path[0].x+b*path[1].x+c*path[2].x+d*path[3].x,y:a*path[0].y+b*path[1].y+c*path[2].y+d*path[3].y}}
function enterRamp(b,name){b.ramp=name;b.rampT=0;b.vx=0;b.vy=0;if(name==='cake'){register('cake');addScore(1800,'CAKE TUNNEL',b.x,b.y);boom('THROUGH THE CAKE!')}else{addScore(900,`${name.toUpperCase()} RAIL`,b.x,b.y);boom(`${name.toUpperCase()} RAIL!`)}tone(name==='cake'?660:520,.18,'triangle',.05)}
function checkRampEntry(b){if(b.ramp||b.vy>-3)return;if(b.y>760&&b.y<855&&b.x>180&&b.x<275)return enterRamp(b,'left');if(b.y>760&&b.y<855&&b.x>610&&b.x<705)return enterRamp(b,'right');if(b.y>750&&b.y<835&&b.x>400&&b.x<482)return enterRamp(b,'cake')}
function rideRamp(b,dt){const path=rampPaths[b.ramp],name=b.ramp;b.rampT+=.017*dt;const p=bezier(path,Math.min(1,b.rampT));b.x=p.x;b.y=p.y;b.trail.push({x:b.x,y:b.y});if(b.trail.length>14)b.trail.shift();if(b.rampT>=1){b.ramp=null;b.rampT=0;b.vx=(path[3].x-path[2].x)*.075;b.vy=(path[3].y-path[2].y)*.075-2;b.spin=name==='left'?.18:name==='right'?-.18:0;say(name==='cake'?'CAKE TUNNEL COMPLETE':'RAIL SHOT COMPLETE')}}
function updateBall(b,dt){if(!b.active)return;if(b.ramp){rideRamp(b,dt);return}b.vy+=.285*dt;b.vx+=b.spin*.012;b.spin*=.988;b.vx*=.997;b.vy*=.998;const speed=Math.hypot(b.vx,b.vy);if(speed>25){b.vx*=25/speed;b.vy*=25/speed}b.x+=b.vx*dt;b.y+=b.vy*dt;b.trail.push({x:b.x,y:b.y});if(b.trail.length>10)b.trail.shift();walls.forEach(w=>lineHit(b,...w,.76));imageRails.forEach(w=>lineHit(b,...w,.72));targets.filter(o=>o.id!=='cake').forEach(o=>targetHit(b,o));pegs.forEach(p=>targetHit(b,{...p,r:12,pts:100,id:'post',label:'POST'}));slings.forEach(s=>{if(lineHit(b,s.x1,s.y1,s.x2,s.y2,.93,2.8))addScore(250,'SLINGSHOT',b.x,b.y)});checkRampEntry(b);flippers.forEach(f=>flipperHit(b,f))}
function endBall(){ballNumber++;tone(55,.3,'sawtooth');if(ballNumber>3){running=false;clearInterval(musicTimer);if(score>high.score){ui.initials.classList.add('show');$('#initials').focus()}else showGameOver()}else{resetBall();hud();say(`BALL ${ballNumber} — HOLD TO LAUNCH`)}}
function showGameOver(){ui.card.querySelector('.eyebrow').textContent='FINAL SCORE';ui.card.querySelector('h1').innerHTML=`${score.toLocaleString()}<br><em>POINTS!</em>`;ui.card.querySelector('p').textContent=`High score: ${high.initials} — ${high.score.toLocaleString()}`;ui.card.querySelector('#start').textContent='PLAY AGAIN';ui.card.classList.remove('hidden')}
function update(dt){if(!running||paused)return;if(charging){charge=(Math.sin(performance.now()/480-Math.PI/2)+1)/2;updateMeter()}const leftTarget=keys.left?-.44:flippers[0].rest,rightTarget=keys.right?Math.PI+.44:flippers[1].rest;flippers.forEach((f,i)=>{const pressed=i?keys.right:keys.left,target=i?rightTarget:leftTarget,diff=target-f.a;f.omega=f.omega*.42+diff*(pressed?.38:.24);f.omega=Math.max(-.22,Math.min(.22,f.omega));if(Math.abs(diff)<.004&&Math.abs(f.omega)<.008){f.a=target;f.omega=0}else f.a+=f.omega});balls.forEach(b=>updateBall(b,Math.min(1.45,dt)));for(let i=balls.length-1;i>=0;i--)if(balls[i].y>1115)balls.splice(i,1);if(!balls.length)endBall();targets.forEach(t=>t.hit=Math.max(0,(t.hit||0)-.045));particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.12;p.t-=.025});particles=particles.filter(p=>p.t>0);floaters.forEach(f=>{f.y-=1.2;f.t-=.018});floaters=floaters.filter(f=>f.t>0);shake*=.86}
function drawTarget(t){if(!t.hit)return;ctx.beginPath();ctx.arc(t.x,t.y,t.r+8+t.hit*12,0,7);ctx.lineWidth=6;ctx.strokeStyle=t.c;ctx.globalAlpha=t.hit;ctx.shadowColor=t.c;ctx.shadowBlur=25;ctx.stroke();ctx.shadowBlur=0;ctx.globalAlpha=1}function draw(){ctx.save();ctx.clearRect(0,0,W,H);if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);ctx.fillStyle='#061923';ctx.fillRect(0,0,W,H);if(img.complete)ctx.drawImage(img,0,0,W,H);ctx.fillStyle='rgba(0,0,0,.12)';ctx.fillRect(50,405,790,700);ctx.lineCap='round';ctx.lineWidth=4;ctx.strokeStyle='rgba(255,185,65,.28)';walls.forEach(w=>{ctx.beginPath();ctx.moveTo(w[0],w[1]);ctx.lineTo(w[2],w[3]);ctx.stroke()});targets.forEach(drawTarget);candles.forEach((c,i)=>{if(mission===1&&i<progress.size){ctx.beginPath();ctx.arc(c.x,c.y,7+Math.sin(performance.now()/100+i)*2,0,7);ctx.fillStyle='#fff6a8';ctx.shadowColor='#ff6b21';ctx.shadowBlur=18;ctx.fill();ctx.shadowBlur=0}});party.forEach((p,i)=>{if(mission===2&&i<progress.size){ctx.font='bold 22px Archivo Black';ctx.fillStyle='#58d5ea';ctx.shadowColor='#58d5ea';ctx.shadowBlur=15;ctx.fillText(p.l,p.x,p.y);ctx.shadowBlur=0}});flippers.forEach(f=>{const ex=f.x+Math.cos(f.a)*f.len,ey=f.y+Math.sin(f.a)*f.len;ctx.beginPath();ctx.moveTo(f.x,f.y);ctx.lineTo(ex,ey);ctx.lineWidth=27;ctx.strokeStyle='rgba(244,224,170,.95)';ctx.stroke();ctx.lineWidth=6;ctx.strokeStyle='#d44a22';ctx.stroke()});balls.forEach(b=>{b.trail.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x,p.y,2+i/2,0,7);ctx.fillStyle=`rgba(88,213,234,${i/b.trail.length*.4})`;ctx.fill()});ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);const g=ctx.createRadialGradient(b.x-4,b.y-5,2,b.x,b.y,b.r);g.addColorStop(0,'#fff');g.addColorStop(.35,'#d8e2e4');g.addColorStop(1,'#53656c');ctx.fillStyle=g;ctx.shadowColor='#fff';ctx.shadowBlur=13;ctx.fill();ctx.shadowBlur=0});ctx.textAlign='center';ctx.font='bold 28px Chivo Mono';ctx.fillStyle='#ff8a2b';ctx.fillText(String(score).padStart(7,'0'),443,360);particles.forEach(p=>{ctx.globalAlpha=p.t;ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,5,5)});floaters.forEach(f=>{ctx.globalAlpha=f.t;ctx.font='bold 18px Archivo Black';ctx.fillStyle='#fff4b3';ctx.fillText(f.text,f.x,f.y)});ctx.globalAlpha=1;ctx.restore();requestAnimationFrame(loop)}function loop(t){update((t-last)/16.67||1);last=t;draw()}
function key(e,on){if(['ArrowLeft','a','A'].includes(e.key)){keys.left=on;e.preventDefault()}if(['ArrowRight','d','D'].includes(e.key)){keys.right=on;e.preventDefault()}if(e.code==='Space'){on?startCharge():releaseLaunch();e.preventDefault()}if(on&&e.key.toLowerCase()==='r')newGame();if(on&&e.key.toLowerCase()==='p')togglePause()}
addEventListener('keydown',e=>key(e,true));addEventListener('keyup',e=>key(e,false));function hold(id,k){const el=$(id);['pointerdown','pointerup','pointercancel','pointerleave'].forEach(ev=>el.addEventListener(ev,e=>{keys[k]=ev==='pointerdown';e.preventDefault()}))}hold('#left-btn','left');hold('#right-btn','right');const launchBtn=$('#launch-btn');launchBtn.onpointerdown=e=>{startCharge();e.preventDefault()};launchBtn.onpointerup=launchBtn.onpointercancel=launchBtn.onpointerleave=e=>{releaseLaunch();e.preventDefault()};$('#start').onclick=newGame;ui.pauseBtn.onclick=()=>togglePause();$('#resume').onclick=()=>togglePause(false);$('#sound').onclick=e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?'SOUND ON':'SOUND OFF';soundOn?partyBeat():clearInterval(musicTimer)};$('#fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():$('.machine').requestFullscreen();$('#save-score').onclick=()=>{const initials=($('#initials').value.toUpperCase().replace(/[^A-Z0-9]/g,'')+'---').slice(0,3);high={score,initials};localStorage.setItem('martyPartyHigh',JSON.stringify(high));ui.initials.classList.remove('show');hud();showGameOver()};document.addEventListener('visibilitychange',()=>{if(document.hidden&&running&&!paused)togglePause(true)});canvas.onclick=()=>canvas.focus();hud();resetBall();requestAnimationFrame(loop);

// Enhanced compositing makes the digital ball feel embedded in the photographed machine.
draw=function(){ctx.save();ctx.clearRect(0,0,W,H);if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);ctx.fillStyle='#061923';ctx.fillRect(0,0,W,H);if(img.complete)ctx.drawImage(img,0,0,W,H);ctx.fillStyle='rgba(0,0,0,.08)';ctx.fillRect(55,405,780,700);targets.forEach(t=>{if(t.hit){const glow=ctx.createRadialGradient(t.x,t.y,4,t.x,t.y,t.r*1.8);glow.addColorStop(0,t.c+'bb');glow.addColorStop(1,'transparent');ctx.globalCompositeOperation='screen';ctx.fillStyle=glow;ctx.fillRect(t.x-t.r*2,t.y-t.r*2,t.r*4,t.r*4);ctx.globalCompositeOperation='source-over'}drawTarget(t)});imageRails.forEach(w=>{ctx.beginPath();ctx.moveTo(w[0],w[1]);ctx.lineTo(w[2],w[3]);ctx.lineWidth=3;ctx.strokeStyle='rgba(255,193,78,.22)';ctx.stroke()});candles.forEach((c,i)=>{if(mission===1&&i<progress.size){ctx.beginPath();ctx.arc(c.x,c.y,7+Math.sin(performance.now()/100+i)*2,0,7);ctx.fillStyle='#fff6a8';ctx.shadowColor='#ff6b21';ctx.shadowBlur=18;ctx.fill();ctx.shadowBlur=0}});party.forEach((p,i)=>{if(mission===2&&i<progress.size){ctx.font='bold 22px Archivo Black';ctx.fillStyle='#58d5ea';ctx.shadowColor='#58d5ea';ctx.shadowBlur=15;ctx.fillText(p.l,p.x,p.y);ctx.shadowBlur=0}});flippers.forEach(f=>{const ex=f.x+Math.cos(f.a)*f.len,ey=f.y+Math.sin(f.a)*f.len;ctx.beginPath();ctx.moveTo(f.x,f.y);ctx.lineTo(ex,ey);ctx.lineWidth=25;ctx.strokeStyle='rgba(244,224,170,.92)';ctx.stroke();ctx.lineWidth=5;ctx.strokeStyle='#b83d20';ctx.stroke()});balls.forEach(b=>{b.trail.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x,p.y,1+i/3,0,7);ctx.fillStyle=`rgba(88,213,234,${i/b.trail.length*.2})`;ctx.fill()});ctx.beginPath();ctx.ellipse(b.x+7,b.y+10,b.r*.92,b.r*.62,.35,0,7);ctx.fillStyle='rgba(0,0,0,.55)';ctx.filter='blur(3px)';ctx.fill();ctx.filter='none';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);const g=ctx.createRadialGradient(b.x-5,b.y-6,1,b.x,b.y,b.r);g.addColorStop(0,'#fff');g.addColorStop(.28,'#dce5e7');g.addColorStop(.7,'#84969d');g.addColorStop(1,'#33474f');ctx.fillStyle=g;ctx.shadowColor='rgba(255,244,210,.7)';ctx.shadowBlur=7;ctx.fill();ctx.shadowBlur=0});if(img.complete)occluders.forEach(r=>ctx.drawImage(img,r[0],r[1],r[2],r[3],r[0],r[1],r[2],r[3]));ctx.textAlign='center';ctx.font='bold 28px Chivo Mono';ctx.fillStyle='#ff8a2b';ctx.shadowColor='#ff5b20';ctx.shadowBlur=7;ctx.fillText(String(score).padStart(7,'0'),443,360);ctx.shadowBlur=0;particles.forEach(p=>{ctx.globalAlpha=p.t;ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,5,5)});floaters.forEach(f=>{ctx.globalAlpha=f.t;ctx.font='bold 18px Archivo Black';ctx.fillStyle='#fff4b3';ctx.fillText(f.text,f.x,f.y)});ctx.globalAlpha=1;ctx.restore();requestAnimationFrame(loop)};
function coverFlipper(f,a){ctx.beginPath();ctx.moveTo(f.x-Math.cos(a)*5,f.y-Math.sin(a)*5);ctx.lineTo(f.x+Math.cos(a)*(f.len+6),f.y+Math.sin(a)*(f.len+6));ctx.lineCap='round';ctx.lineWidth=38;ctx.strokeStyle='rgba(8,25,31,.94)';ctx.stroke()}
function drawPhotoFlipper(f){coverFlipper(f,f.rest);coverFlipper(f,f.a);const delta=f.a-f.rest;ctx.save();ctx.translate(f.x,f.y);ctx.rotate(f.a);ctx.beginPath();ctx.roundRect(-17,-18,f.len+34,36,18);ctx.clip();ctx.rotate(-f.a);ctx.translate(-f.x,-f.y);ctx.translate(f.x,f.y);ctx.rotate(delta);ctx.translate(-f.x,-f.y);ctx.drawImage(img,0,0,W,H);ctx.restore();ctx.beginPath();ctx.arc(f.x,f.y,15,0,Math.PI*2);ctx.fillStyle='rgba(236,183,73,.78)';ctx.fill()}
const imageIntegratedDraw=draw;draw=function(){imageIntegratedDraw();if(img.complete)flippers.forEach(drawPhotoFlipper)};
